cache:
  paths:
    - node_modules/

stages:
  - build_deploy
  - lint

lint_backend:
  image: node:24
  stage: lint
  script:
    - cd backend
    - npm install -g pnpm
    - pnpm install
    - npm run lint

lint_frontend:
  image: node:24
  stage: lint
  script:
    - cd frontend
    - npm install -g pnpm
    - pnpm install
    - npm run lint


build_deploy:
  stage: build_deploy
  image: docker
  services:
  - docker:dind
  script:
    - docker build -t "$ACR_REPOSITORY" .
    - docker login "$ACR_REPOSITORY" -u "$ACR_USERNAME" -p "$ACR_PASSWORD"
    - docker push "$ACR_REPOSITORY"

