default:
  image: node

cache:
  paths:
    - node_modules/

include:
  # 1: include the component
  - component: $CI_SERVER_FQDN/to-be-continuous/azure/gitlab-ci-azure@3.0.3
    # 2: set/override component inputs
    inputs:
      base-app-name: spankki
      review-enabled: true
      staging-enabled: true
      prod-enabled: true

stages:
  - install
  - lint
  - build
  - deploy

install:
  stage: install
  script:
    - npm install -g pnpm
    #- docker compose up -d
    - cd backend
    - pnpm install
    #- pnpm run db:migrate
    #- pnpm run db:seed
    - cd ..
    - cd frontend
    - pnpm install

lint_backend:
  stage: lint
  script:
    - cd backend
    - npm install -g pnpm
    - pnpm install
    - npm run lint

lint_frontend:
  stage: lint
  script:
    - cd frontend
    - npm install -g pnpm
    - pnpm install
    - npm run lint

build:
  stage: build
  script:
    - cd backend
    - npm install -g typescript
    - tsc
    - cd ../frontend
    - npm install -g typescript
    - tsc

deploy:
  stage: deploy
  script:
    - cd backend
    - node ./dist/index.js


